version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  proxy:
    #image: vesica/proxy.waf.network:latest
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - proxy-memcached
    depends_on:
      - proxy-memcached
    environment:
      MEMCACHED_HOST: "proxy-memcached"
      MEMCACHED_PORT: "11211"
      PROXY_URL: "https://website.url"
      WAF_PROXY_NAMESPACE: "MyNameSpace"
      WAF_CONFIG_URL: "http://vesica.ws/waf.yml" # This is just a test file
      WAF_CONFIG_EXPIRY: "300"
      WAF_KEY: "CBqTh2mE6g"
      LOG_LEVEL: "DEBUG"
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: xproxy

  #######################################
  # Memcached
  #######################################
  proxy-memcached:
    image: memcached:1.5
    container_name: xproxy-memcached

  #######################################
  # Memcached Admin
  #######################################
  proxy-memadmin:
    image: vesica/memadmin:latest
    ports:
      - "7074:8080"
    environment:
      MEMADMIN_USERNAME: proxy
      MEMADMIN_PASSWORD: proxy
      MEMCACHED_HOST: xproxy-memcached
      MEMCACHED_PORT: 11211
    container_name: xproxy-memadmin
