# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: vesica/php72
    # Memcached container
    - image: memcached:1.5
    working_directory: /var/www

    # Setup Service and Create Database
    steps:
    - run: composer install

    # Store Artifacts
    #- store_artifacts:
    #    path: /app/build
