# Note that values separated with a comma are always OR and each of the global keys are always AND
blacklist:
  - name: my blacklist # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["123.456.78.9", "77.99.90.3/27"]
        #USER_AGENT: [Mozilla/5.0, python-requests/2.8]
      server: # required
        REMOTE_ADDR: ["1.1.1.1"]
      #    QUERY_STRING: [one=yes&two=no&three=maybe]