config:
  url: example.com
  waf_url: example.proxy.waf.network
  ips: [12.12.12.12, 13.13.13.14] # destination IPs in order of tries
  ssl:
    enable: true or alse
    force: true or false:
    settings:
      certificate:
      key:
      ca: