# Note that values separated with a comma are always OR and each of the global keys are always AND
global:
  geoblock:
    countries: [ae, gb, us]
  blacklist:
    ips: [123.456.78.9, 78.99.90.3]
    user_agents: [Mozilla/5.0, python-requests/2.8]
    http_referers: [http://something.com, 'something else']
    http_cookies: [cookie_one, another_cookie]
    url_paths: [path/one, path/two]
    query_strings: [key=value, key2=value2, key3, :key4] # key3 exists, key4 does not exist
    headers: [name=vaue, name2=value2, name, :anothername] # name exists, anothername does not exist
  whitelist:
    ips: [123.456.78.9, 78.99.90.3]
    user_agents: [Mozilla/5.0, python-requests/2.8]
    http_referers: [http://something.com, 'something else']
    http_cookies: [cookie_one, another_cookie]
    url_paths: [path/one, path/two]
    query_strings: [key=value, key2=value2, key3, :key4]
    headers: [name=vaue, name2=value2, name, :anothername] # name exists, anothername does not exist
  ratelimit:
    per_day:
      ips:
        - {123.456.78.9: 10000}
    per_hour:
      ips:
        - {123.456.78.9: 500}
        - {123.456.78.9: 500}
      user_agents:
        - {python-reuqests/2.8: 10}
        - {123.456.78.9: 500}
    per_minute:
      ips:
        - {123.456.78.9: 60}
      http_referers:
        - {http://somesite, 5}
    per_second:
      ips:
        - {123.456.78.9: 60}
      http_cookies:
        - {choc_cookie: 5}
